worker_processes 1;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events { worker_connections 1024; }

http {
	access_log /dev/stdout;
	sendfile on;
	client_max_body_size 2g;
	client_body_temp_path /tmp/client_body;
	proxy_temp_path /tmp/proxy_temp;
	fastcgi_temp_path /tmp/fastcgi_temp;
	uwsgi_temp_path /tmp/uwsgi_temp;
	scgi_temp_path /tmp/scgi_temp;

	map $http_upgrade $connection_upgrade {
		default upgrade;
		''      close;
	}
	map $http_upgrade $backend {
		default http://web:9080;
		websocket http://proxy:8081;
	}

	include /etc/nginx/mime.types;
	default_type application/octet-stream;
	types {
		application/wasm wasm;
	}

	server {
		listen 8080;
		server_name _;

		location = /hello {
			proxy_pass http://web:9080;
			proxy_set_header Host $host;
		}
		location = /slist {
			proxy_pass http://proxy:8081;
			proxy_set_header Host $host;
		}
		location = /resolve {
			proxy_pass http://proxy:8081;
			proxy_set_header Host $host;
		}

		location / {
			proxy_pass $backend;
			proxy_http_version 1.1;
			proxy_set_header Host $host;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection $connection_upgrade;
			proxy_read_timeout 3600s;
			proxy_send_timeout 3600s;
		}
	}
}
